before_commands:
    - "composer install --no-interaction --prefer-dist --no-scripts"

build:
    environment:
        php:
            version: 7.1.0

tools:
    external_code_coverage:
        timeout: 1800
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        enabled: false
    php_cpd:
        enabled: true
        excluded_dirs: ["test", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["src/*", "test/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["test", "vendor"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["test", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*", "test/*"]
    sensiolabs_security_checker: true
